"use client";

import { useRouter } from "next/navigation";
import {
  Newspaper, Wifi, RefreshCw, PackageSearch,
  ShieldAlert, Truck, Lightbulb, Copy, Check,
  RotateCcw, Clock,
} from "lucide-react";
import { useState } from "react";
import { cn, formatCurrency } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import type {
  StockoutRisk,
  BriefingAnomaly,
  SupplierWatch,
} from "@/app/(dashboard)/insights/briefing/page";

// ── Helpers ────────────────────────────────────────────────────────────────

function fmtWeek(iso: string): string {
  if (!iso) return "";
  const d = new Date(iso);
  return d.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
}

function fmtGenerated(iso: string | null): string {
  if (!iso) return "";
  return new Date(iso).toLocaleString("en-GB", {
    day: "numeric", month: "short", hour: "2-digit", minute: "2-digit",
  });
}

// ── Severity chip ──────────────────────────────────────────────────────────

function SeverityChip({ severity }: { severity: "critical" | "warning" }) {
  return (
    <span
      className={cn(
        "text-[9px] font-bold px-1.5 py-0.5 rounded uppercase tracking-wide",
        severity === "critical"
          ? "bg-red-100 text-red-700"
          : "bg-amber-100 text-amber-700"
      )}
    >
      {severity}
    </span>
  );
}

// ── Props ──────────────────────────────────────────────────────────────────

interface Props {
  weekStart: string;
  prose: string;
  recommendation: string;
  stockoutRisks: StockoutRisk[];
  biggestAnomaly: BriefingAnomaly | null;
  supplierWatch: SupplierWatch | null;
  currency: string;
  fromCache: boolean;
  generatedAt: string | null;
  unavailable: boolean;
}

// ── Email text builder ─────────────────────────────────────────────────────

function buildEmailText(weekStart: string, prose: string, recommendation: string): string {
  return `Subject: SUPPLIQ Weekly AI Briefing — Week of ${weekStart}

${prose}

---
Key action this week: ${recommendation}

Generated by SUPPLIQ AI · ${new Date().toLocaleDateString("en-GB")}`;
}

// ── Main component ──────────────────────────────────────────────────────────

export function BriefingClient({
  weekStart, prose, recommendation, stockoutRisks, biggestAnomaly,
  supplierWatch, currency, fromCache, generatedAt, unavailable,
}: Props) {
  const router    = useRouter();
  const [copied, setCopied] = useState(false);

  // ── Offline ───────────────────────────────────────────────────────────────
  if (unavailable) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center space-y-3">
        <Wifi className="h-10 w-10 text-slate-300" />
        <h3 className="font-semibold text-slate-600">AI service is offline</h3>
        <p className="text-sm text-slate-400 max-w-sm">
          Start it with <code className="bg-slate-100 px-1 rounded text-xs">uvicorn main:app --port 8000</code> inside <code className="bg-slate-100 px-1 rounded text-xs">ai/</code>, then refresh.
        </p>
        <Button variant="outline" size="sm" className="gap-1.5 mt-2" onClick={() => router.refresh()}>
          <RefreshCw className="h-3.5 w-3.5" />
          Retry
        </Button>
      </div>
    );
  }

  // ── No briefing (shouldn't happen — endpoint always generates) ────────────
  if (!prose) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center space-y-3">
        <Newspaper className="h-10 w-10 text-slate-300" />
        <p className="text-sm text-slate-400">No briefing available yet.</p>
        <Button size="sm" onClick={() => router.push("/insights/briefing?force=1")}>
          Generate now
        </Button>
      </div>
    );
  }

  function handleCopy() {
    const text = buildEmailText(fmtWeek(weekStart), prose, recommendation);
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  return (
    <div className="space-y-5 max-w-3xl">

      {/* ── Header ──────────────────────────────────────────────────────── */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-xl font-bold text-slate-800 flex items-center gap-2">
            <Newspaper className="h-5 w-5 text-amber-500" />
            AI Weekly Briefing
          </h1>
          <p className="text-sm text-slate-500 mt-0.5">
            Week of {fmtWeek(weekStart)}
            {generatedAt && (
              <span className="ml-2 text-slate-400 inline-flex items-center gap-1">
                <Clock className="h-3 w-3" />
                Generated {fmtGenerated(generatedAt)}
                {fromCache && <span className="text-slate-300">· cached</span>}
              </span>
            )}
          </p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5"
            onClick={handleCopy}
          >
            {copied ? <Check className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
            {copied ? "Copied!" : "Copy as email"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            className="gap-1.5"
            onClick={() => router.push("/insights/briefing?force=1")}
          >
            <RotateCcw className="h-3.5 w-3.5" />
            Regenerate
          </Button>
        </div>
      </div>

      {/* ── Prose ────────────────────────────────────────────────────────── */}
      <div className="rounded-xl border border-amber-200 bg-amber-50 px-5 py-4">
        <div className="flex items-start gap-3">
          <div className="rounded-full bg-amber-100 border border-amber-200 p-1.5 shrink-0 mt-0.5">
            <Newspaper className="h-3.5 w-3.5 text-amber-600" />
          </div>
          <div className="space-y-3">
            <p className="text-[10px] font-bold uppercase tracking-wider text-amber-500">
              Monday briefing · AI-generated prose
            </p>
            {prose.split(/\n\n+/).filter(Boolean).map((para, i) => (
              <p key={i} className="text-sm text-amber-900 leading-relaxed">
                {para.trim()}
              </p>
            ))}
          </div>
        </div>
      </div>

      {/* ── Recommendation callout ────────────────────────────────────────── */}
      {recommendation && (
        <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 flex items-start gap-3">
          <Lightbulb className="h-4 w-4 text-blue-500 shrink-0 mt-0.5" />
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-blue-500 mb-0.5">
              This week&apos;s key action
            </p>
            <p className="text-sm text-blue-900">{recommendation}</p>
          </div>
        </div>
      )}

      {/* ── Supporting data ───────────────────────────────────────────────── */}
      <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-400">
        Data behind the briefing
      </p>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">

        {/* Stockout risks */}
        <div className="rounded-xl border border-slate-200 p-3">
          <div className="flex items-center gap-1.5 mb-2">
            <PackageSearch className="h-3.5 w-3.5 text-red-500" />
            <span className="text-xs font-semibold text-slate-700">Stockout risks</span>
          </div>
          {stockoutRisks.length === 0 ? (
            <p className="text-xs text-slate-400">No items critically low.</p>
          ) : (
            <ul className="space-y-2">
              {stockoutRisks.map((r, i) => (
                <li key={i} className="text-xs">
                  <p className="font-medium text-slate-800 leading-tight truncate">{r.item_name}</p>
                  <p className="text-slate-500 font-mono text-[10px]">{r.sku}</p>
                  <p className={cn(
                    "font-semibold tabular-nums mt-0.5",
                    r.days_left <= 3 ? "text-red-600" : r.days_left <= 7 ? "text-amber-600" : "text-slate-600"
                  )}>
                    {r.days_left}d left · {r.stock_qty} units
                  </p>
                  {r.branch && <p className="text-[10px] text-slate-400">{r.branch}</p>}
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Biggest anomaly */}
        <div className="rounded-xl border border-slate-200 p-3">
          <div className="flex items-center gap-1.5 mb-2">
            <ShieldAlert className="h-3.5 w-3.5 text-orange-500" />
            <span className="text-xs font-semibold text-slate-700">Biggest anomaly</span>
          </div>
          {!biggestAnomaly ? (
            <p className="text-xs text-slate-400">No anomalies detected this week.</p>
          ) : (
            <div className="space-y-1">
              <div className="flex items-center gap-1.5 flex-wrap">
                <SeverityChip severity={biggestAnomaly.severity} />
                <span className="text-[10px] font-mono text-slate-500 uppercase">
                  {biggestAnomaly.type.replace(/_/g, " ")}
                </span>
              </div>
              <p className="text-xs font-medium text-slate-800 leading-tight">
                {biggestAnomaly.entity_name}
              </p>
              {biggestAnomaly.description && (
                <p className="text-[10px] text-slate-500 leading-snug">
                  {biggestAnomaly.description}
                </p>
              )}
            </div>
          )}
        </div>

        {/* Supplier watch */}
        <div className="rounded-xl border border-slate-200 p-3">
          <div className="flex items-center gap-1.5 mb-2">
            <Truck className="h-3.5 w-3.5 text-slate-500" />
            <span className="text-xs font-semibold text-slate-700">Supplier to watch</span>
          </div>
          {!supplierWatch ? (
            <p className="text-xs text-slate-400">No supplier concerns.</p>
          ) : (
            <div className="space-y-1">
              <p className="text-xs font-semibold text-slate-800 leading-tight">
                {supplierWatch.supplier_name}
              </p>
              <p className="text-[10px] text-slate-500">
                Avg lead time:{" "}
                <span className={cn(
                  "font-semibold",
                  supplierWatch.avg_lead_days > 14 ? "text-red-600" :
                  supplierWatch.avg_lead_days > 7  ? "text-amber-600" : "text-slate-700"
                )}>
                  {supplierWatch.avg_lead_days} days
                </span>
              </p>
              <p className="text-[10px] text-slate-400">
                Based on {supplierWatch.order_count} received order{supplierWatch.order_count !== 1 ? "s" : ""}
              </p>
            </div>
          )}
        </div>
      </div>

      <p className="text-[10px] text-slate-400 pt-1">
        Briefing generated every Monday at 08:00 UTC by the SUPPLIQ AI scheduler.
        Use &quot;Copy as email&quot; to paste into your mail client for team distribution.
        &quot;Regenerate&quot; forces a fresh briefing with current data.
      </p>
    </div>
  );
}
