"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import {
  AlertTriangle, PackageSearch, Wifi, RefreshCw, ChevronDown, ChevronUp, Lock,
} from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";
import { cn } from "@/lib/utils";
import { QuickReorderDialog } from "@/components/insights/quick-reorder-dialog";
import type { ReorderRecommendation } from "@/app/(dashboard)/insights/reorder/page";
import type { SupplierRow } from "@/lib/actions/suppliers";

// ── Priority config ────────────────────────────────────────────────────────

const PRIORITY_CONFIG = {
  critical: {
    label: "Critical",
    badge: "bg-red-100 text-red-700 border-red-300",
    row:   "bg-red-50/40",
  },
  high: {
    label: "High",
    badge: "bg-amber-100 text-amber-700 border-amber-300",
    row:   "bg-amber-50/30",
  },
  medium: {
    label: "Medium",
    badge: "bg-yellow-50 text-yellow-700 border-yellow-200",
    row:   "",
  },
  low: {
    label: "Low",
    badge: "bg-slate-100 text-slate-500 border-slate-200",
    row:   "",
  },
} as const;

// ── Stat card ──────────────────────────────────────────────────────────────

function StatCard({ value, label, colour }: { value: number; label: string; colour: string }) {
  return (
    <div className={cn("rounded-lg border px-4 py-3 text-center", colour)}>
      <p className="text-2xl font-bold tabular-nums">{value}</p>
      <p className="text-xs mt-0.5 opacity-70">{label}</p>
    </div>
  );
}

// ── Reasoning expand/collapse ──────────────────────────────────────────────

function ReasoningCell({ text }: { text: string }) {
  const [open, setOpen] = useState(false);
  const short = text.length > 120 ? text.slice(0, 120) + "…" : text;
  return (
    <div className="max-w-xs">
      <p className="text-[11px] text-slate-500 leading-relaxed">
        {open ? text : short}
      </p>
      {text.length > 120 && (
        <button
          onClick={() => setOpen((o) => !o)}
          className="mt-0.5 flex items-center gap-0.5 text-[10px] text-blue-500 hover:text-blue-700"
        >
          {open ? <ChevronUp className="h-2.5 w-2.5" /> : <ChevronDown className="h-2.5 w-2.5" />}
          {open ? "Less" : "More"}
        </button>
      )}
    </div>
  );
}

// ── Props ──────────────────────────────────────────────────────────────────

interface Props {
  recommendations: ReorderRecommendation[];
  suppliers: Pick<SupplierRow, "id" | "name">[];
  branches: { id: string; name: string }[];
  currency: string;
  isAdmin: boolean;
  defaultBranchId: string | null;
  unavailable: boolean;
  criticalCount: number;
  highCount: number;
  plan: string;
}

// ── Main component ─────────────────────────────────────────────────────────

export function ReorderClient({
  recommendations,
  suppliers,
  branches,
  currency,
  isAdmin,
  defaultBranchId,
  unavailable,
  criticalCount,
  highCount,
  plan,
}: Props) {
  const router = useRouter();
  const [selected, setSelected] = useState<ReorderRecommendation | null>(null);
  const [priorityFilter, setPriorityFilter] = useState<"all" | "critical" | "high" | "medium" | "low">("all");

  const isGrowthMode = plan === "GROWTH";
  const displayedRecs = isGrowthMode ? recommendations.slice(0, 5) : recommendations;
  const totalCount = recommendations.length;

  const filtered = priorityFilter === "all"
    ? displayedRecs
    : displayedRecs.filter((r) => r.priority === priorityFilter);

  function handleSuccess() {
    setSelected(null);
    router.refresh();
  }

  // ── AI service offline ──────────────────────────────────────────────────
  if (unavailable) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center space-y-3">
        <Wifi className="h-10 w-10 text-slate-300" />
        <h3 className="font-semibold text-slate-600">AI service is offline</h3>
        <p className="text-sm text-slate-400 max-w-sm">
          Reorder recommendations are generated by the SUPPLIQ AI service.
          Start it with <code className="bg-slate-100 px-1 rounded text-xs">python -m uvicorn main:app --port 8000</code> inside the <code className="bg-slate-100 px-1 rounded text-xs">ai/</code> directory.
        </p>
        <Button variant="outline" size="sm" className="gap-1.5 mt-2" onClick={() => router.refresh()}>
          <RefreshCw className="h-3.5 w-3.5" />
          Retry
        </Button>
      </div>
    );
  }

  // ── No recommendations ──────────────────────────────────────────────────
  if (recommendations.length === 0) {
    return (
      <div className="space-y-4">
        <PageHeader count={0} criticalCount={0} highCount={0} />
        <div className="flex flex-col items-center justify-center py-24 text-center space-y-2">
          <PackageSearch className="h-10 w-10 text-green-300" />
          <h3 className="font-semibold text-slate-600">All items well-stocked</h3>
          <p className="text-sm text-slate-400">
            No items are below their reorder threshold right now.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <PageHeader count={totalCount} criticalCount={criticalCount} highCount={highCount} />

      {/* Stats + filter row */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex gap-2">
          <StatCard
            value={criticalCount}
            label="Critical"
            colour="border-red-200 bg-red-50 text-red-700"
          />
          <StatCard
            value={highCount}
            label="High"
            colour="border-amber-200 bg-amber-50 text-amber-700"
          />
          <StatCard
            value={recommendations.length - criticalCount - highCount}
            label="Medium / Low"
            colour="border-slate-200 bg-slate-50 text-slate-600"
          />
        </div>

        <select
          value={priorityFilter}
          onChange={(e) => setPriorityFilter(e.target.value as typeof priorityFilter)}
          className="h-9 rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
        >
          <option value="all">All priorities</option>
          <option value="critical">Critical only</option>
          <option value="high">High only</option>
          <option value="medium">Medium only</option>
          <option value="low">Low only</option>
        </select>
      </div>

      {/* Table */}
      <div className="rounded-lg border border-slate-200 bg-white overflow-hidden [&_th]:h-8 [&_th]:py-2 [&_th]:text-[11px] [&_td]:py-2 [&_td]:align-top">
        <Table>
          <TableHeader>
            <TableRow className="bg-slate-50 hover:bg-slate-50">
              <TableHead className="w-24">Priority</TableHead>
              <TableHead className="min-w-[180px]">Item</TableHead>
              <TableHead className="w-28">Branch</TableHead>
              <TableHead className="w-24 text-right">Stock / ROP</TableHead>
              <TableHead className="w-24 text-right">Days left</TableHead>
              <TableHead className="w-24 text-right">Suggest qty</TableHead>
              {!isGrowthMode && <TableHead className="min-w-[200px]">AI reasoning</TableHead>}
              <TableHead className="w-28 text-right">Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filtered.length === 0 ? (
              <TableRow>
                <TableCell colSpan={isGrowthMode ? 7 : 8} className="py-10 text-center text-slate-400 text-xs">
                  No items match this filter.
                </TableCell>
              </TableRow>
            ) : (
              filtered.map((rec, i) => {
                const cfg = PRIORITY_CONFIG[rec.priority];
                const daysLeft = rec.estimated_days_until_stockout;
                const daysColour =
                  daysLeft === null ? "text-slate-400" :
                  daysLeft <= 3    ? "text-red-600 font-bold" :
                  daysLeft <= 7    ? "text-amber-600 font-semibold" : "text-slate-600";
                return (
                  <TableRow key={`${rec.item_id}-${rec.branch_id}-${i}`} className={cn("transition-colors", cfg.row)}>
                    <TableCell>
                      <Badge className={cn("text-[10px] font-semibold border px-1.5 py-0", cfg.badge)}>
                        {cfg.label}
                      </Badge>
                    </TableCell>

                    <TableCell>
                      <p className="font-medium text-xs text-slate-800">{rec.item_name}</p>
                      <p className="text-[10px] text-slate-400 font-mono">{rec.sku}</p>
                    </TableCell>

                    <TableCell className="text-xs text-slate-500 whitespace-nowrap">
                      {rec.branch_name}
                    </TableCell>

                    <TableCell className="text-right whitespace-nowrap">
                      <span className="text-xs font-semibold text-slate-700">{rec.current_stock}</span>
                      <span className="text-[10px] text-slate-400"> / {rec.reorder_point}</span>
                    </TableCell>

                    <TableCell className="text-right whitespace-nowrap">
                      <span className={cn("text-xs tabular-nums", daysColour)}>
                        {daysLeft !== null ? `~${daysLeft}d` : "—"}
                      </span>
                    </TableCell>

                    <TableCell className="text-right whitespace-nowrap">
                      <span className="text-xs font-semibold text-blue-700 tabular-nums">
                        {rec.suggested_order_qty}
                      </span>
                      <p className="text-[9px] text-slate-400">avg {rec.avg_daily_demand}/day</p>
                    </TableCell>

                    {!isGrowthMode && (
                      <TableCell>
                        <ReasoningCell text={rec.reasoning} />
                      </TableCell>
                    )}

                    <TableCell className="text-right">
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-7 text-xs gap-1 border-blue-200 text-blue-700 hover:bg-blue-50 hover:border-blue-300"
                        onClick={() => setSelected(rec)}
                      >
                        <AlertTriangle className="h-3 w-3" />
                        Order
                      </Button>
                    </TableCell>
                  </TableRow>
                );
              })
            )}
          </TableBody>
        </Table>
      </div>

      {isGrowthMode && totalCount > 5 ? (
        <Link
          href="/settings/billing"
          className="flex items-center gap-2 text-xs text-slate-500 border border-dashed border-slate-300 rounded-lg px-4 py-2.5 hover:bg-slate-50 transition-colors w-fit"
        >
          <Lock className="h-3.5 w-3.5 text-slate-400" />
          Showing top 5 of {totalCount} items. Upgrade to Enterprise for the full list with AI reasoning.
        </Link>
      ) : (
        <p className="text-[11px] text-slate-400">
          Showing {filtered.length} of {totalCount} items · Reorder points are AI-calculated from demand forecasts
        </p>
      )}

      <QuickReorderDialog
        rec={selected}
        suppliers={suppliers}
        branches={branches}
        currency={currency}
        isAdmin={isAdmin}
        defaultBranchId={defaultBranchId}
        onClose={() => setSelected(null)}
        onSuccess={handleSuccess}
      />
    </div>
  );
}

// ── Page header ────────────────────────────────────────────────────────────

function PageHeader({ count, criticalCount, highCount }: { count: number; criticalCount: number; highCount: number }) {
  return (
    <div className="flex items-center justify-between">
      <div>
        <h1 className="text-xl font-bold text-slate-800 flex items-center gap-2">
          <PackageSearch className="h-5 w-5 text-blue-500" />
          Reorder Alerts
        </h1>
        <p className="text-sm text-slate-500 mt-0.5">
          {count === 0
            ? "All items are well-stocked"
            : `${count} item${count !== 1 ? "s" : ""} below reorder threshold${criticalCount > 0 ? ` · ${criticalCount} critical` : ""}${highCount > 0 ? ` · ${highCount} high` : ""}`}
          {" · "}
          <span className="text-[11px] text-blue-500">AI-powered · ROPs update nightly</span>
        </p>
      </div>
    </div>
  );
}
