"""
Demand Forecasting Service

What this will do:
  1. Pull 90 days of daily sales per (item, branch) from the DB
  2. Apply a time-series model to each series:
       - Baseline: exponential smoothing (handles seasonality + trend)
       - Upgrade path: SARIMA → Prophet → LSTM as data grows
  3. Detect day-of-week and month seasonality patterns
  4. Output predicted_demand + confidence_score per (item, branch, period)
  5. Write results to the `forecasts` table via db.upsert_forecast()

Confidence score logic:
  - High (0.85+): 60+ days of consistent sales history
  - Medium (0.60–0.85): 30–60 days or noisy series
  - Low (<0.60): sparse data, new items, or high variance

Model versioning: increment model_version on algorithm changes so the
Next.js app can detect when a forecast was generated by an old model.
"""

from datetime import datetime, timedelta

from utils.db import get_sales_history, upsert_forecast


MODEL_VERSION = "v0.1-ema"


def _exponential_moving_average(values: list[float], alpha: float = 0.3) -> float:
    """Single exponential smoothing - returns the next-period forecast."""
    if not values:
        return 0.0
    ema = values[0]
    for v in values[1:]:
        ema = alpha * v + (1 - alpha) * ema
    return round(ema, 4)


def _confidence_from_history(n_days: int, cv: float) -> float:
    """
    cv = coefficient of variation (std / mean) of the sales series.
    More data + less variance → higher confidence.
    """
    data_score = min(n_days / 60.0, 1.0)          # saturates at 60 days
    noise_score = max(0.0, 1.0 - min(cv, 1.0))    # 0 cv = perfect, >1 cv = noisy
    return round(0.5 * data_score + 0.5 * noise_score, 4)


async def run_demand_forecast(
    org_id: str,
    item_id: str | None,
    branch_id: str | None,
    horizon_days: int = 30,
) -> list[dict]:
    """
    Main entry point. Returns a list of forecast dicts ready for upsert_forecast().

    TODO (implementation phases):
    Phase 1 - ship: EMA on raw daily qty per (item, branch)
    Phase 2 - improve: add day-of-week seasonal index
    Phase 3 - scale: switch to Facebook Prophet for automatic seasonality
    Phase 4 - ML: LSTM for high-volume items with 1 year of history
    """
    rows = await get_sales_history(org_id, item_id, branch_id, days=90)

    # Group rows by (item_id, branch_id)
    series: dict[tuple[str, str], list[float]] = {}
    for row in rows:
        key = (row["item_id"], row["branch_id"])
        series.setdefault(key, []).append(float(row["total_qty"]))

    now = datetime.utcnow()
    period_start = now.replace(hour=0, minute=0, second=0, microsecond=0) + timedelta(days=1)
    period_end = period_start + timedelta(days=horizon_days)

    results = []
    for (iid, bid), daily_qtys in series.items():
        if not daily_qtys:
            continue

        # Reverse so oldest first (DB returns desc)
        daily_qtys = list(reversed(daily_qtys))

        predicted_daily = _exponential_moving_average(daily_qtys)
        predicted_total = predicted_daily * horizon_days

        import statistics
        mean = statistics.mean(daily_qtys)
        if mean > 0:
            cv = statistics.stdev(daily_qtys) / mean if len(daily_qtys) > 1 else 0.5
        else:
            cv = 1.0

        confidence = _confidence_from_history(len(daily_qtys), cv)

        # Reorder suggestion: will stock out within horizon_days?
        # (Actual stock lookup handled by optimization.reorder - this just flags it)
        reorder_suggested = confidence >= 0.5 and predicted_total > 0

        results.append({
            "item_id": iid,
            "branch_id": bid,
            "organization_id": org_id,
            "period_start": period_start,
            "period_end": period_end,
            "predicted_demand": round(predicted_total, 2),
            "confidence_score": confidence,
            "reorder_suggested": reorder_suggested,
            "suggested_qty": None,  # filled in by reorder optimizer
            "model_version": MODEL_VERSION,
        })

    return results
